name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true
  NODE_VERSION: 18
  SOLANA_VERSION: 1.18.12

jobs:
  build_programs:
    name: Build programs
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/setup
        with:
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-programs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-programs
      - name: Build programs
        run: pnpm programs:build
      - name: Upload program builds
        uses: actions/upload-artifact@v4
        with:
          name: program-builds
          path: ./target/deploy/*.so
          if-no-files-found: error
      - name: Save all builds for clients
        uses: actions/cache/save@v4
        with:
          path: ./**/*.so
          key: ${{ runner.os }}-builds-${{ github.head_ref }}-${{ github.sha }}

  test_programs:
    name: Test programs
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/setup
        with:
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}
      - name: Cache test cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-program-tests-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-program-tests
            ${{ runner.os }}-programs-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-programs
      - name: Test programs
        run: pnpm programs:test

  generate_idls:
    name: Generate IDLs
    needs: build_programs
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/setup
        with:
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-programs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-programs
      - name: Cache local cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            .cargo/bin/
            .cargo/registry/index/
            .cargo/registry/cache/
            .cargo/git/db/
          key: ${{ runner.os }}-local-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-local-cargo
      - name: Generate IDLs
        run: pnpm generate:idls
      - name: Ensure working directory is clean
        run: test -z "$(git status --porcelain)"

  generate_clients:
    name: Generate clients
    needs: generate_idls
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/setup
        with:
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}
      - name: Generate clients
        run: pnpm generate:clients
      - name: Ensure working directory is clean
        run: test -z "$(git status --porcelain)"

  test_js:
    name: Test JS client
    needs: generate_clients
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/setup
        with:
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}
      - name: Restore all builds
        uses: actions/cache/restore@v4
        with:
          path: ./**/*.so
          key: ${{ runner.os }}-builds-${{ github.head_ref }}-${{ github.sha }}
      - name: Test JS client
        run: pnpm clients:js:test

  # test_rust_client:
  #   if: needs.changes.outputs.rust_client == 'true'
  #   name: Rust Client
  #   needs: generate_clients
  #   uses: ./.github/workflows/test-rust-client.yml
  #   secrets: inherit
